from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(792, 501)
        Form.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(250, 200, 101, 31))
        font = QtGui.QFont()
        font.setItalic(True)
        font.setUnderline(True)
        font.setStrikeOut(False)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(Form)
        self.comboBox_2.setGeometry(QtCore.QRect(600, 200, 101, 31))
        font = QtGui.QFont()
        font.setItalic(True)
        font.setUnderline(True)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(Form)
        self.comboBox_3.setGeometry(QtCore.QRect(250, 320, 101, 31))
        font = QtGui.QFont()
        font.setItalic(True)
        font.setUnderline(True)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_4 = QtWidgets.QComboBox(Form)
        self.comboBox_4.setGeometry(QtCore.QRect(600, 320, 101, 31))
        font = QtGui.QFont()
        font.setItalic(True)
        font.setUnderline(True)
        self.comboBox_4.setFont(font)
        self.comboBox_4.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(150, 20, 461, 131))
        font = QtGui.QFont()
        font.setFamily("Sitka Text Semibold")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255,163,26);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(100, 200, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255,163,26);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(100, 320, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255,163,26);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(450, 200, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255,163,26);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(450, 320, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255,163,26);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(-310, 390, 491, 361))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(r"C:\Users\12345\Documents\GitHub\Topix\pictures\romb.png"))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(620, -220, 241, 331))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(r"C:\Users\12345\Documents\GitHub\Topix\pictures\romb.png"))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(-330, -200, 471, 301))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(r"C:\Users\12345\Documents\GitHub\Topix\pictures\romb.png"))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(580, 390, 1111, 391))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap(r"C:\Users\12345\Documents\GitHub\Topix\pictures\romb.png"))
        self.label_9.setObjectName("label_9")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(330, 410, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Text Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(255,163,26);")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.comboBox.setItemText(0, _translate("Form", "любой"))
        self.comboBox.setItemText(1, _translate("Form", "драма"))
        self.comboBox.setItemText(2, _translate("Form", "криминал"))
        self.comboBox.setItemText(3, _translate("Form", "триллер"))
        self.comboBox.setItemText(4, _translate("Form", "комедия"))
        self.comboBox.setItemText(5, _translate("Form", "боевик"))
        self.comboBox.setItemText(6, _translate("Form", "приключения"))
        self.comboBox.setItemText(7, _translate("Form", "детектив"))
        self.comboBox.setItemText(8, _translate("Form", "фэнтези"))
        self.comboBox.setItemText(9, _translate("Form", "мелодрама"))
        self.comboBox.setItemText(10, _translate("Form", "мультфильм"))
        self.comboBox.setItemText(11, _translate("Form", "ужасы"))
        self.comboBox.setItemText(12, _translate("Form", "биография"))
        self.comboBox.setItemText(13, _translate("Form", "фантастика"))
        self.comboBox.setItemText(14, _translate("Form", "вестерн"))
        self.comboBox_2.setItemText(0, _translate("Form", "любой"))
        self.comboBox_2.setItemText(1, _translate("Form", ">2020"))
        self.comboBox_2.setItemText(2, _translate("Form", "2010-2020"))
        self.comboBox_2.setItemText(3, _translate("Form", "2000-2010"))
        self.comboBox_2.setItemText(4, _translate("Form", "1990-2000"))
        self.comboBox_2.setItemText(5, _translate("Form", "1980-1990"))
        self.comboBox_2.setItemText(6, _translate("Form", "1970-1980"))
        self.comboBox_2.setItemText(7, _translate("Form", "<1970"))
        self.comboBox_3.setItemText(0, _translate("Form", "любая"))
        self.comboBox_3.setItemText(1, _translate("Form", "США"))
        self.comboBox_3.setItemText(2, _translate("Form", "Великобритания"))
        self.comboBox_3.setItemText(3, _translate("Form", "Россия"))
        self.comboBox_3.setItemText(4, _translate("Form", "Франция"))
        self.comboBox_3.setItemText(5, _translate("Form", "Япония"))
        self.comboBox_4.setItemText(0, _translate("Form", "любая"))
        self.comboBox_4.setItemText(1, _translate("Form", "60 - 120 минут"))
        self.comboBox_4.setItemText(2, _translate("Form", "120 - 180 минут"))
        self.comboBox_4.setItemText(3, _translate("Form", ">180 минут"))
        self.label.setText(_translate("Form", "Критерии поиска фильма"))
        self.label_2.setText(_translate("Form", "ЖАНР"))
        self.label_3.setText(_translate("Form", "СТРАНА"))
        self.label_4.setText(_translate("Form", "ГОД"))
        self.label_5.setText(_translate("Form", "ДЛИНА"))
        self.pushButton.setText(_translate("Form", "Найти"))
